### ISSUE TITLE
the link to the "what is bibex?" from every single abs page is busted

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-docs#104]
**Describe the bug**
Going to https://labs.arxiv.org/projects/bibexplorer results in a 404

**To Reproduce**
1. Go to https://labs.arxiv.org/projects/bibexplorer
2. See the 404
3. ???
4. No profit.

**Expected behavior**
Not a 404. Preferably a page with content.

**Additional context**
d'oh

**Comment by mhl10** [comment]
This was fixed.
