### ISSUE TITLE
Incomplete rreplacement documentation

### ISSUE THREAD

**Issue by pkoppenb** [arXiv/arxiv-docs#273]
In https://arxiv.org/help/replace it says "The exceptions to this rule are the addition of journal reference and DOI information." One FAQ we have in LHCb is whether adding a report number triggers a new version. It turns out it does not, but regularly users point to this page to back up the opposite argument. Could you please explicitly write that new report numbers do not trigger new versions? Thanks. Patrick

**Comment by jimentwood** [comment]
Good point. Will update that text in next deployment of arxiv-docs

**Comment by pkoppenb** [comment]
Thanks
