### ISSUE TITLE
Incorrect description of the build system

### ISSUE THREAD

**Issue by akhmerov** [arXiv/arxiv-docs#409]
The utilities page states that arXiv uses teTeX as its LaTeX build system: https://github.com/arXiv/arxiv-docs/blob/1c8c5b2646dfa9c812ac5121a6e85d6f9c9a5a7e/mkdocs/docs/help/utilities.md#tex

This is outdated because the arXiv blog stated that arXiv uses TeXlive 2020 already in 2020: https://blog.arxiv.org/2020/11/12/error-detected-a-new-feature-helps-authors-submit-their-work/

**Comment by jweiskoff** [comment]
Thank you for the helpful feedback. We'll review the items on this page, and get it updated to our current best practices and data.
