### ISSUE TITLE
setup pretty subheadings in navigation

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-docs#441]
Currently the mkdocs navigation appears to display folders in Camel Case.
The folders in legacy were not written with correct case so those could be corrected. 
Example /help/oa to /help/OA
The display in mkdocs would need to be configured to preserve the as written folder case
Example
OA would appear as OA instead of currently what happens is the legacy written folder "oa" is displayed as "Oa"
![image](https://user-images.githubusercontent.com/11538356/202748943-003c5b81-723d-4dc4-a4b5-216fd52fde6a.png)

**Comment by bdc34** [comment]
The solution to this is to change the `source/help/cs` directory to `source/help/CS`

**Comment by jimentwood** [comment]
Resolved by having custom nav plugin
