### ISSUE TITLE
For Later - Reorg pages in Help

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-docs#442]
The Help pages have 80+ pages in the root directory. They should all be reorganized into a small set of main folders like
Submit
Read/Find
Policies
API and Bulk Data Users

When the reorg happens, the redirects for the pages need to be tracked.
The links inside all pages that refer to the moved page also need to be updated.

**Comment by alisonhofer** [comment]
@jimentwood is this still relevant?

**Comment by jimentwood** [comment]
I would say yes, there is a need to reorganize material and navigation around most common user journeys, but it doesn't have to be tracked as an issue here.

**Comment by jweiskoff** [comment]
This should be tracked in our normal ticketing, doesn't need to be tracked here.
