### ISSUE TITLE
setup pretty urls - remove index.html and .html suffix requirements

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-docs#443]
We want to preserve the benefit of the legacy markdown display that allowed for urls like
arxiv.org/help/moderation

The MVP for mkdocs adds extra string to the urls that make them more difficult to share in daily operations and in outreach with print materials. For example that page turns into 
arxiv.org/help/moderation/index.html

**Comment by bdc34** [comment]
This link works fine and redirects correctly: https://docs.arxiv.org/help/moderation
