### ISSUE TITLE
unclear what the #filename.md# means

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-docs#444]
In this directory 
https://github.com/arXiv/arxiv-docs/tree/develop/source/help/stats
there is
index.md which I updated to be current
there is also "#index.md#" which is not current.

If I see things with hashmarks like #filename.md# can they just be deleted? or are they part of mkdocs process?

![image](https://user-images.githubusercontent.com/11538356/202789208-5ce864ee-89c6-4a1a-9aac-43dadf513dee.png)

**Comment by bdc34** [comment]
That looks like some backup file from someone's editor.
It can be deleted.
