### ISSUE TITLE
"Submissions by Category" link broken at https://info.arxiv.org/help/stats/index.html

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-docs#451]
I think the markdown is correct??
`-   [Submissions by Category](/about/reports/submission_category_by_year.md)`

but the link is not getting converted... it still appears as
`<a href="[/about/reports/submission_category_by_year.md](https://info.arxiv.org/about/reports/submission_category_by_year.md)">Submissions by Category</a></li>`

This page exists OK
https://info.arxiv.org/about/reports/submission_category_by_year.html

**Comment by jimentwood** [comment]
These links also resolved to .md extensions on that page

`
<li><a href="[/about/reports/2020_usage.md](https://info.arxiv.org/about/reports/2020_usage.md)">Annual institutional downloads</a></li>
</ul>
<p><em>Explore more <a href="[/about/reports/2020_usage.md](https://info.arxiv.org/about/reports/2020_usage.md)">arXiv in Numbers 2020</a>
`

**Comment by SBBCornell** [comment]
only a .html extension works at the moment. We need a redirect from .md to .html to fix universally, or we could try a gigantic find-and-replace but that seems more error prone.

**Comment by SBBCornell** [comment]
Fixed by changing the links to [Submissions by Category](../../about/reports/submission_category_by_year.md)
