### ISSUE TITLE
Search by date missing from the API docs

### ISSUE THREAD

**Issue by akhmerov** [arXiv/arxiv-docs#526]
**Describe the bug**
Already in 2009 there was an undocumented search by date: https://groups.google.com/g/arxiv-api/c/mAFYT2VRpK0/m/hGTScrUUndwJ

I believe it is still not documented.

**To Reproduce**

Check [the query construction part of the API user docs](https://github.com/arXiv/arxiv-docs/blob/cdab22f9d0fc646d4779b82cafa72e92b61dcb84/source/help/api/user-manual.md#51-details-of-query-construction) for the mention of a search by submission date. Observe that the search by submission date isn't mentioned.

**Expected behavior**
Search by submission date is documented in that section.

**Comment by binhle113** [comment]
> **Describe the bug**
> Already in 2009 there was an undocumented search by date: https://groups.google.com/g/arxiv-api/c/mAFYT2VRpK0/m/hGTScrUUndwJ
> 
> I believe it is still not documented.
> 
> **To Reproduce**
> 
> Check [the query construction part of the API user docs](https://github.com/arXiv/arxiv-docs/blob/cdab22f9d0fc646d4779b82cafa72e92b61dcb84/source/help/api/user-manual.md#51-details-of-query-construction) for the mention of a search by submission date. Observe that the search by submission date isn't mentioned.
> 
> **Expected behavior**
> Search by submission date is documented in that section.
>

**Comment by alans3321** [comment]
> **Describe the bug** Already in 2009 there was an undocumented search by date: https://groups.google.com/g/arxiv-api/c/mAFYT2VRpK0/m/hGTScrUUndwJ
> 
> I believe it is still not documented.
> 
> **To Reproduce**
> 
> Check [the query construction part of the API user docs](https://github.com/arXiv/arxiv-docs/blob/cdab22f9d0fc646d4779b82cafa72e92b61dcb84/source/help/api/user-manual.md#51-details-of-query-construction) for the mention of a search by submission date. Observe that the search by submission date isn't mentioned.
> 
> **Expected behavior** Search by submission date is documented in that section.

**Comment by jweiskoff** [comment]
Fixed in https://github.com/arXiv/arxiv-docs/pull/1034
