### ISSUE TITLE
Broken link on 3rd party submissions page

### ISSUE THREAD

**Issue by tomresing** [arXiv/arxiv-docs#558]
**Describe the bug**
Link to Microsoft Conference Management toolkit broken

**To Reproduce**
1. Go to https://info.arxiv.org/help/third_party_submission.html
2. Click on link 
3. See error

**Expected behavior**
Reach the page described

**Comment by jweiskoff** [comment]
Thanks for redirecting the link, @tomresing. I'll close this, as the changes will be live in production about 10 minutes or so after the merge.

**Comment by tomresing** [comment]
Looks good love on the site. Thanks for reviewing and merging so quickly!
