### ISSUE TITLE
searching the source of a graph: "ML + AI arXiv papers per month", someone is using this but does not show the original source of the graph. 

### ISSUE THREAD

**Issue by ggmanloveAI** [arXiv/arxiv-docs#587]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jonathanhyoung** [comment]
I believe that the original graph in question appears as Figure 1 in https://arxiv.org/pdf/2210.00881.pdf .  The caption is "Number of papers published per months in the arXiv categories of AI grow exponentially. The doubling rate of papers per months is roughly 23 months, which might lead to problems for publishing in these fields, at some point. The categories are cs.AI, cs.LG, cs.NE, and stat.ML."
