### ISSUE TITLE
arXiv documentation does not mention where a paper password can be recovered from

### ISSUE THREAD

**Issue by SeSodesa** [arXiv/arxiv-docs#617]
**Is your feature request related to a problem? Please describe.**

Currently, neither the Passwords documentation page ([link](https://info.arxiv.org/help/passwords.html)) or the Authority records page ([link](https://info.arxiv.org/help/authority.html)) mention, where exactly a paper password can be recovered from. I just had to go to Google and StackExchange (specifically a comment by LudvigH of [this answer](https://academia.stackexchange.com/a/54814)) to find this out, so I could instruct a submitting author where they could find it.

**Describe the solution you'd like**

A short mention on both the Password and Authority records pages regarding where a paper password can be found, once a paper has been submitted. Currently a paper password is received in the confirmation e-mail of a submitted article.

**Describe alternatives you've considered**

There really are no better alternatives. This is very simple to implement, not very time consuming and the best option in terms of accessibility. I don't think anyone wants to spend the time to make a video on this?

**Additional context**

Some authors are not aware of the possibility of linking the arXiv accounts of other authors to a paper, so they do not pay attention to the part of the e-mail that tells the paper password, when it is first received. This is how I ended up looking for this information.

**Comment by SeSodesa** [comment]
Might be closed by #618.

**Comment by jweiskoff** [comment]
Closed by #619
