### ISSUE TITLE
typo on author page

### ISSUE THREAD

**Issue by o12johns** [arXiv/arxiv-docs#646]
**Describe the bug**
On the author page the third dot item in the preflight check box reads:
"Common errors that slow down announcement include mission files or bibliography."
It should read:
"Common errors that slow down announcement include missing files or bibliography."

**Desktop (please complete the following information):**
 - OS: MACOS 13.0
 - Browser: Firefox 115.0.3

**Comment by jweiskoff** [comment]
Thank you for reaching out with this issue. We are aware of the typo, but it is not contained within this particular repository.
