### ISSUE TITLE
Logos download is hidden behind a registration link

### ISSUE THREAD

**Issue by pbelmans** [arXiv/arxiv-docs#662]
**Describe the bug**
The logos download is hidden behind a registration link.

**To reproduce**
1. Go to [the logos page](https://info.arxiv.org/brand/logos.html)
2. Click on any of the download links, e.g., [Large Logomark in PNG format](https://cornell.box.com/v/arxiv-logomark-png)
3. Choose '[Not a part of Cornell-Ithaca & Cornell Tech](https://account.box.com/login?redirect_url=https://cornell.app.box.com/v/arxiv-logomark-png)'
4. Need to sign in to Box.com

**Expected behavior**
A download link which doesn't require registration.

**Comment by cbf66** [comment]
We should be showing public links to private places.

**Comment by alisonhofer** [comment]
We have updated the permissions to the logos and they are now fully accessible without a login to Box.
