### ISSUE TITLE
None of the links from https://info.arxiv.org/about/accessibility_html_papers.html work

### ISSUE THREAD

**Issue by BarrySmith** [arXiv/arxiv-docs#774]
**Describe the bug**
None of the links from https://info.arxiv.org/about/accessibility_html_papers.html work

**To Reproduce**
Go to  https://info.arxiv.org/about/accessibility_html_papers.html work and click on one of paper links

**Expected behavior**
It would go to the paper

**Desktop (please complete the following information):**
 -macOS
 - Safari
 -

**Additional context**
Should be fixed quickly since this is a newly released feature and it is a bit embarrassing that one cannot look at the canned examples you provided of HTML papers.

**Comment by RizwanJdr** [comment]
URL structure was not correct
submitted a PR #782
