### ISSUE TITLE
Need credit for licensing 

### ISSUE THREAD

**Issue by Griffin641498** [arXiv/arxiv-docs#799]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheNthTerwilliger** [comment]
If this has to do with me, and I am incredibly unclear about how all this works, but I'm trying to ensure the safety of my life and my mother's, and seeing as how I have no civil rights where I live now I am trying to be the Most pleasant eager to learn monkey strapped to a barrel, as long as it is of great benefit to the world at large, and fuses my full name and clearly states that I have tried many times to settle things in a peaceful, forgiving, and humorous way, then you have my full on support to do what is needed.l
