### ISSUE TITLE
Description for the `stat` classification is missing

### ISSUE THREAD

**Issue by maikol-solis** [arXiv/arxiv-docs#809]
**Describe the bug**
There is no information for the `stat` classification. 

**To Reproduce**
1. Go to https://info.arxiv.org/help/stat/index.html
2. See missing page 404 - Not found. 

**Expected behavior**
Information about the `stat` classification, and what does it mean each subclass: [Applications](https://arxiv.org/list/stat.AP/recent); [Computation](https://arxiv.org/list/stat.CO/recent); [Machine Learning](https://arxiv.org/list/stat.ML/recent); [Methodology](https://arxiv.org/list/stat.ME/recent); [Other Statistics](https://arxiv.org/list/stat.OT/recent); [Statistics Theory](https://arxiv.org/list/stat.TH/recent)

**Screenshots**

![image](https://github.com/arXiv/arxiv-docs/assets/4078489/bc98256a-3021-42b8-a16e-617557cbf5c2)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 102

**Additional context**
NA

**Comment by maikol-solis** [comment]
Hi! 

The information I'm looking for is in this file https://github.com/arXiv/arxiv-docs/blob/master/source/help/statistics/index.md

Maybe it's just a bad link somewhere.

**Comment by maikol-solis** [comment]
And yes, I clicked on the "detailed description" link in the statistical section.

**Comment by alisonhofer** [comment]
Thank you for the clarification! 
The page you are seeking is this one: https://info.arxiv.org/help/statistics/index.html#AdvisoryCommittee
Which is linked from: https://info.arxiv.org/about/people/editorial_advisory_council.html. 

Let me know if there is anything else I can help with. 
Cheers.

**Comment by maikol-solis** [comment]
Thanks for the clarification. Yes, this exactly the information that I'm looking for. 

Just to notice that in the main page https://arxiv.org/ if you go down to the Statistics section 

![image](https://github.com/arXiv/arxiv-docs/assets/4078489/1665386f-8d14-4c01-aecc-87e527bc0370)


The "detailed description" redirects to the mentioned 404 page before.

**Comment by alisonhofer** [comment]
Thank you, for pointing that out. I will open a ticket and get that resolved as soon as possible.

**Comment by alisonhofer** [comment]
This issue has been resolved.
We appreciate your patience.
