### ISSUE TITLE
Spelling error in API manual (<author>)

### ISSUE THREAD

**Issue by LopezBanos** [arXiv/arxiv-docs#827]
**Describe the bug**
The result object entry key <author> is wrong, but provided by the API manual (https://info.arxiv.org/help/api/user-manual.html#_details_of_atom_results_returned)

**To Reproduce**
1. Do an arXiv search and get a results object.
2. Iterate over the generator `for r in client.results.(search):`
3. Try to print `r.author'

**Expected behavior**
Output the author names. To get the expected behavior you have to `r.authors` with the 's'. In the API manual an 's' is missing.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version Not relevant

**Comment by jweiskoff** [comment]
Are you certain you're looking at the Atom? there's no `<authors>` element defined in our specifications. If you're querying the JSON feed elsewhere, the data fields may have different names.

**Comment by LopezBanos** [comment]
If you use the python package and try to get the <author> without the s you get the following error:
```python

AttributeError: 'Result' object has no attribute 'author'
```
But if you use authors (with the 's') then everything works.

**Comment by jweiskoff** [comment]
what package(s) are you using, and please provide a mwe that shows the error? Your steps to replicate are incomplete.

**Comment by LopezBanos** [comment]
Hopefully this screenshot will clarify my point:
![swappy-20240326-203724](https://github.com/arXiv/arxiv-docs/assets/87113552/ca2d5e97-4617-4cfd-ae23-016637b50eb8)

**Comment by jweiskoff** [comment]
Can you point at the `arxiv` package you're using? I suspect it isn't arXiv-maintained code.

**Comment by LopezBanos** [comment]
`arxiv                     2.1.0                    pypi_0    pypi`
WebSite: https://pypi.org/project/arxiv/

**Comment by jweiskoff** [comment]
This is using a custom wrapper around the output to display the content other than what's being natively returned by arXiv's API (which returns native Atom that you'd have to parse). It is not arXiv's code (so the documentation here is not actually incorrect). I suggest you reach out to Lucas (who's been in contact with us before) for more information about how he's structured the output object within the code.

**Comment by LopezBanos** [comment]
Ok I see. Could you send me Lucas GitHub or mail?

Thanks for your quick answer

**Comment by jweiskoff** [comment]
Here: https://github.com/lukasschwab/arxiv.py
