### ISSUE TITLE
Undocumented filename length limit of 100 characters

### ISSUE THREAD

**Issue by fKunstner** [arXiv/arxiv-docs#940]
**Describe the bug**
Submissions fail if they include files with names longer than `100` characters.

**To Reproduce**
1. Create a new submission at https://arxiv.org/submit/
2. Upload the following test files:

   - `main.tex`:
   
     ```
     \documentclass{article}
     \begin{document}
     \input{0000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999hi.tex}
     \end{document}
     ```  

   - `0000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999hi.tex`:
     ```
     hi
     ```

4. Scroll down to uploaded files. The filename reads `0000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999` (missing `hi.tex`)

5. Trying to compile results in a `File not found`

   ```
   ! LaTeX Error: File    `0000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999abcdef.tex' not found.
   ```

**Expected behavior**
This behavior is not unexpected in hindsight, but it is difficult to diagnose. The above submission can work locally, depending on the total path length.

The upload page should present a warning that file names have been truncated and need to be changed to <100 characters (including file extensions).

This should be documented in https://info.arxiv.org/help/faq/mistakes.html as it is not covered by the existing file name specific entries:
- [Absolute filenames](https://info.arxiv.org/help/faq/mistakes.html#absolute-filenames)
- [Spaces and other inappropriate characters in filenames](https://info.arxiv.org/help/faq/mistakes.html#upper-case-vs-lower-case-filenames)
- [Upper-case vs Lower-case filenames](https://info.arxiv.org/help/faq/mistakes.html#spaces-and-other-inappropriate-characters-in-filenames)

**Comment by jweiskoff** [comment]
cannot reproduce using MWE. 

```tex
\documentclass{article}

%testing len limit
\begin{filecontents}{000000000011111111112222222222333333333344444444445555555555666666666777777777788888888889999999999abcdef.tex}
Hi.
\end{filecontents}
\begin{document}
\input{000000000011111111112222222222333333333344444444445555555555666666666777777777788888888889999999999abcdef}

\end{document}
```
produces a pdf in arXiv.
