### ISSUE TITLE
Bad link for Python API package feedparser

### ISSUE THREAD

**Issue by vaneseltine** [arXiv/arxiv-docs#999]
**Describe the bug**

Links to feedparser.org are no longer helpful, since it has been over 2 years since that website has been associated with the Python feedparser package.

**To Reproduce**

1. Go to [API User Manual 4.2. Detailed Parsing Examples](https://info.arxiv.org/help/api/user-manual.html#detailed_examples)
2. Click on "feedparser" link
3. Be redirected to soccerprose.com
4. Discover yourself at an Indonesian gambling site

**Expected behavior**

You discover useful information about feedparser, such as its [GitHub homepage](https://github.com/kurtmckee/feedparser) or [documentation](https://feedparser.readthedocs.io/).

**Comment by alisonhofer** [comment]
Thanks for the heads up on this.
